[package]
name = "SpotiCLI"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.1"
curl = "0.4.47"
dotenv = "0.15.0"
reqwest = "0.12.9"
